'use client';
import { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export default function SecurityPanel() {
  const [factorId, setFactorId] = useState(''), [qr, setQr] = useState(''), [secret, setSecret] = useState(''), [verified, setVerified] = useState(false), [assured, setAssured] = useState(false), [code, setCode] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function load() { const factors = await supabase!.auth.mfa.listFactors(); const factor = factors.data?.totp.find(f => f.status === 'verified'); setFactorId(factor?.id || ''); setVerified(!!factor); const level = await supabase!.auth.mfa.getAuthenticatorAssuranceLevel(); setAssured(level.data?.currentLevel === 'aal2'); }
  useEffect(() => { void load(); }, []);
  async function enroll() { setBusy(true); setError(''); try { const pending = await supabase!.auth.mfa.listFactors(); for (const f of pending.data?.all.filter(f => f.factor_type === 'totp' && f.status === 'unverified') || []) await supabase!.auth.mfa.unenroll({ factorId: f.id }); const { data, error } = await supabase!.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Riyasat owner' }); if (error) throw error; setFactorId(data.id); setQr(data.totp.qr_code); setSecret(data.totp.secret); } catch (e) { setError(e instanceof Error ? e.message : 'Could not set up authentication.'); } finally { setBusy(false); } }
  async function verify(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const { error } = await supabase!.auth.mfa.challengeAndVerify({ factorId, code }); if (error) throw error; setQr(''); setSecret(''); setCode(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Code could not be verified.'); } finally { setBusy(false); } }
  return <section className="panel security-panel"><div className="section-title"><h2>Account security</h2><ShieldCheck size={22} /></div><p>Owners must verify an authenticator code before changing live records or granting access.</p>{assured ? <p className="positive">Two-factor authentication verified for this session.</p> : <>{!verified && !qr && <button className="primary" disabled={busy} onClick={() => void enroll()}>Set up authenticator</button>}{qr && <><p>Scan this code with your authenticator app. Keep your recovery access secure.</p><img src={qr} alt="Authenticator setup QR code" width={180} height={180} /><details><summary>Manual setup key</summary><code>{secret}</code></details></>}{factorId && <form onSubmit={verify}><label>Six-digit authenticator code<input value={code} onChange={e => setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required /></label><button className="primary" disabled={busy}>{busy ? 'Verifying…' : verified ? 'Verify this session' : 'Activate two-factor authentication'}</button></form>}</>}{error && <p className="form-error" role="alert">{error}</p>}</section>;
}
