export type Role = 'owner' | 'manager' | 'viewer';
export type Actor = { id: string; name: string; role: Role; propertyIds: string[] | null };
export type Property = { id: string; name: string; address: string; city: string; state: string; country: string; latitude?: number; longitude?: number; archived?: boolean };
export type Floor = { id: string; propertyId: string; name: string; order: number };
export type Unit = { id: string; propertyId: string; floorId: string; name: string; kind: string; area: number; order: number; width: number; archived?: boolean };
export type Tenant = { id: string; propertyId: string; name: string; email: string; phone: string; notes: string };
export type Lease = { id: string; propertyId: string; unitIds: string[]; tenantId: string; rent: number; deposit: number; start: string; end: string; dueDay: number; noticeDays: number; recurring: number; escalationPercent: number; escalationDate: string; ended?: string };
export type Charge = { id: string; propertyId: string; leaseId: string; date: string; due: string; amount: number; kind: 'rent' | 'utility' | 'maintenance'; description: string; key: string };
export type Allocation = { chargeId: string; amount: number; date?: string };
export type Receipt = { id: string; propertyId: string; leaseId: string; date: string; amount: number; withholding: number; kind: 'rent' | 'deposit' | 'advance'; accountId: string; method: string; reference: string; payer: string; collector: string; allocations: Allocation[]; reversed?: boolean; evidence?: string; opening?: boolean };
export type Bill = { id: string; propertyId: string; unitId?: string; date: string; due: string; vendor: string; category: string; amount: number; tax: number; description: string; maintenanceId?: string; evidence?: string; allocations?: { unitId: string; amount: number }[]; recurrence?: 'monthly'; recurrenceEnd?: string; recurrenceParent?: string; key?: string };
export type BillPayment = { id: string; propertyId: string; billId: string; accountId: string; date: string; amount: number; reference: string; reversed?: boolean };
export type Account = { id: string; name: string; kind: 'bank' | 'cash' };
export type JournalLine = { account: string; debit: number; credit: number };
export type Journal = { id: string; propertyId: string; date: string; sourceId: string; description: string; lines: JournalLine[]; reversalOf?: string };
export type Maintenance = { id: string; propertyId: string; unitId: string; title: string; vendor: string; estimate: number; status: 'reported' | 'assigned' | 'in progress' | 'completed' | 'cancelled'; date: string; notes: string };
export type MeterReading = { id: string; propertyId: string; unitId: string; leaseId: string; date: string; previous: number; current: number; rate: number; kind: string };
export type Approval = { id: string; propertyId: string; kind: 'refund' | 'deduction' | 'withdrawal' | 'reversal' | 'writeoff' | 'charge-credit'; amount: number; leaseId?: string; sourceId?: string; accountId: string; date: string; reason: string; requestedBy: string; status: 'pending' | 'approved' | 'rejected'; decidedBy?: string; creditMoves?: { receiptId: string; chargeId: string; amount: number }[] };
export type StatementLine = { id: string; propertyId: string; accountId: string; date: string; description: string; amount: number; fingerprint: string; matchedIds: string[] };
export type Audit = { id: string; actor: string; date: string; action: string; propertyId?: string; detail: string };
export type Evidence = { id: string; propertyId: string; name: string; path: string; sensitive: boolean };
export type WorkspaceState = {
  schemaVersion: 1; name: string; currency: string; timezone: string; fiscalStart: number; reserve: number;
  properties: Property[]; floors: Floor[]; units: Unit[]; tenants: Tenant[]; leases: Lease[];
  charges: Charge[]; receipts: Receipt[]; bills: Bill[]; billPayments: BillPayment[]; accounts: Account[]; journals: Journal[];
  maintenance: Maintenance[]; meters: MeterReading[]; approvals: Approval[]; statements: StatementLine[]; audit: Audit[]; evidence: Evidence[];
  closedThrough: string; commandIds: string[];
};
export type Command = { id: string; type: string; payload: Record<string, unknown> };
export type WorkspaceAccess = { id: string; name: string; actor: Actor };
